name: Atualizar Dados JSON

on:
  schedule:
    - cron: '0 * * * *' # Executa a cada hora. Ajuste conforme necessário.
  workflow_dispatch: # Permite que você execute manualmente para testar.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          pip install requests # Liste suas bibliotecas aqui
          # playwright install

      - name: Executar o scraper
        run: python test/main.py # Caminho para o seu script

      - name: Commit e Push dos arquivos alterados
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"
          
          # Força o rastreamento do arquivo caso ele seja novo ou tenha mudado
          git add test/data.json
          
          # O 'git diff' verifica se houve mudança real para evitar erro de commit vazio
          if git diff --quiet && git diff --staged --quiet; then
            echo "Nenhuma mudança detectada no JSON."
          else
            git commit -m "Auto-update: novos dados coletados"
            git push
          fi
